[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.4.1", features = ["api-all", "cli", "devtools"] }
crc32fast = "1.3.2"
reqwest = { version = "0.11", features = ["blocking"] } 
epub = "1.2.2"
axum = "0.6.19"
tokio = { version = "1.29.1", features = ["full"] }
tower-http = { version = "0.4.3", features = ["fs", "cors"] }
libmobi-rs = { path = "../libmobi-rs/libmobi-rs" }
font-kit = "0.11.0"
async-openai = "0.18.3"
bytes = "1.5.0"
pandoc = "0.8.11"
log = "0.4.20"
env_logger = "0.11.2"
log4rs = "1.3.0"


[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
# This will be used for rust
opt_once_cell = []
